# Generated by Django 4.0.3 on 2022-06-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False)),
                ('joined_date', models.DateField()),
                ('contact', models.CharField(max_length=20)),
                ('teachs', models.CharField(choices=[('secondary', 'secondary'), ('primary', 'primary')], max_length=30)),
            ],
        ),
    ]
