# Generated by Django 4.0.3 on 2022-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_remove_teachers_teachs'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='teachs',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='', max_length=30),
        ),
    ]
