# Generated by Django 4.0.3 on 2022-06-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_teachers_teachs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='status',
            field=models.BooleanField(choices=[('false', 'false'), ('true', 'true')], default=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teachs',
            field=models.CharField(choices=[('secondary', 'secondary'), ('primary', 'primary')], default='', max_length=30),
        ),
    ]
