# Generated by Django 4.0.3 on 2022-06-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0004_alter_teachers_status_alter_teachers_teachs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='teachs',
        ),
        migrations.AddField(
            model_name='teachers',
            name='teaches',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='status',
            field=models.BooleanField(choices=[('true', 'true'), ('false', 'false')], default=False),
        ),
    ]
