# Generated by Django 4.0.3 on 2022-06-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0005_remove_teachers_teachs_teachers_teaches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='status',
            field=models.BooleanField(choices=[('true', 'true'), ('false', 'false')]),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teaches',
            field=models.CharField(choices=[('secondary', 'secondary'), ('primary', 'primary')], default='', max_length=30),
        ),
    ]
