# Generated by Django 4.0.3 on 2022-06-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0006_alter_teachers_status_alter_teachers_teaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='status',
            field=models.BooleanField(choices=[('false', 'false'), ('true', 'true')], default=''),
        ),
    ]
