# Generated by Django 4.0.3 on 2022-06-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0007_alter_teachers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='status',
            field=models.BooleanField(choices=[('true', 'true'), ('false', 'false')], default=''),
        ),
    ]
