# Generated by Django 4.0.3 on 2022-06-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0008_alter_teachers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teaches',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='', max_length=30),
        ),
    ]
