# Generated by Django 4.0.3 on 2022-06-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0010_alter_teachers_status_alter_teachers_teaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='teaches',
            field=models.CharField(choices=[('secondary', 'secondary'), ('primary', 'primary')], default='primary', max_length=30),
        ),
    ]
