# Generated by Django 4.0.3 on 2022-06-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0013_alter_results_title_alter_teachers_teaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='teaches',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='primary', max_length=30),
        ),
    ]
