# Generated by Django 4.0.3 on 2022-06-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0018_notice_result_teacher_delete_results_delete_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=20)),
                ('parentsContact', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('standard', models.CharField(choices=[('ten', 'ten'), ('six', 'six'), ('three', 'three'), ('five', 'five'), ('nine', 'nine'), ('one', 'one'), ('two', 'two'), ('eight', 'eight'), ('four', 'four'), ('seven', 'seven')], max_length=30)),
                ('image', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
