# Generated by Django 4.0.3 on 2022-07-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0020_alter_student_image_alter_student_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='profile1.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='profile2.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII'), (9, 'IX'), (10, 'X')], max_length=30),
        ),
    ]
