# Generated by Django 4.0.3 on 2022-07-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0023_alter_notice_image_alter_result_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='standard',
            field=models.IntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII'), (9, 'IX'), (10, 'X')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
