# Generated by Django 4.0.3 on 2022-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0024_alter_student_image_alter_student_standard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teaches',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='primary', max_length=30),
        ),
    ]
