# Generated by Django 4.0.3 on 2022-07-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0027_alter_notice_image_alter_result_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaches',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='primary', max_length=30),
        ),
    ]
