# Generated by Django 4.0.3 on 2022-07-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0028_teacher_image_alter_teacher_teaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teaches',
            field=models.CharField(choices=[('secondary', 'secondary'), ('primary', 'primary')], default='primary', max_length=30),
        ),
    ]
