# Generated by Django 4.0.3 on 2022-07-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0029_alter_teacher_teaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
